import { University } from "../types";

export const UK_DENTAL_SCHOOLS: University[] = [
  {
    id: "newcastle-1",
    name: "University of Newcastle",
    location: "Newcastle upon Tyne",
    fullAddress: "Newcastle University, Newcastle upon Tyne, NE1 7RU",
    image: "/images/university-1.png",
    admissionStatus: "closed",
    slug: "university-of-newcastle",
    entryRequirements: "AAA",
    studentSatisfaction: 88,
    graduateProspects: 96,
    ucasPoints: 144,
    courseDuration: "5 years",
  },
  {
    id: "kings-college",
    name: "King's College London",
    location: "London",
    fullAddress:
      "King's College London, Strand, London, WC2R 2LS, United Kingdom",
    image: "/images/university-2.png",
    admissionStatus: "open",
    slug: "kings-college-london",
    entryRequirements: "A*AA",
    studentSatisfaction: 82,
    graduateProspects: 98,
    ucasPoints: 152,
    courseDuration: "5 years",
  },
  {
    id: "manchester",
    name: "University of Manchester",
    location: "Manchester",
    fullAddress:
      "The University of Manchester, Oxford Rd, Manchester, M13 9PL, UK",
    image: "/images/university-3.png",
    admissionStatus: "open",
    slug: "university-of-manchester",
    entryRequirements: "AAA",
    studentSatisfaction: 85,
    graduateProspects: 95,
    ucasPoints: 144,
    courseDuration: "5 years",
  },
  {
    id: "cardiff",
    name: "Cardiff University",
    location: "Cardiff",
    fullAddress: "Cardiff University, Cardiff, CF10 3AT, Wales, UK",
    image: "/images/university-4.png",
    admissionStatus: "open",
    slug: "cardiff-university",
    entryRequirements: "AAA",
    studentSatisfaction: 87,
    graduateProspects: 93,
    ucasPoints: 144,
    courseDuration: "5 years",
  },
];
